#监听端口
port = 8197

#日志目录，默认log目录
logpath = "log"

ReqLogLevel = "DEV"


#数据库
[database]
    [[database.default]]
        host     = "192.168.1.5"
        port     = "3306"
        user     = "root"
        pass     = "rootroot"
        name     = "hello1"
        type     = "mysql"