version: "3"
services:
  web:
    image: zw/hello:latest
    volumes:
      - /data/hello1/log:/data/log
    environment:
      - ENV=prod
    network_mode: bridge
    ports:
      - "8197:8197"
    external_links:
       - product_mysql:mysql
       - product_redis:redis
    extra_hosts:
      - "sentry.test.com:111.230.129.170"
