// This code was autogenerated from helloworld.proto, do not edit.
package helloworld

import (
	"context"
	"log"
	"time"

	"github.com/golang/protobuf/proto"
	"github.com/nats-io/nats.go"
	"github.com/nats-rpc/nrpc"
)

// Greeter2Server is the interface that providers of the service
// Greeter2 should implement.
type Greeter2Server interface {
	SayHello(ctx context.Context, req HelloRequest2) (resp HelloReply2, err error)
}

// Greeter2Handler provides a NATS subscription handler that can serve a
// subscription using a given Greeter2Server implementation.
type Greeter2Handler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  Greeter2Server

	encodings []string
}

func NewGreeter2Handler(ctx context.Context, nc nrpc.NatsConn, s Greeter2Server) *Greeter2Handler {
	return &Greeter2Handler{
		ctx:    ctx,
		nc:     nc,
		server: s,

		encodings: []string{"protobuf"},
	}
}

func NewGreeter2ConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s Greeter2Server) *Greeter2Handler {
	return &Greeter2Handler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

// SetEncodings sets the output encodings when using a '*Publish' function
func (h *Greeter2Handler) SetEncodings(encodings []string) {
	h.encodings = encodings
}

func (h *Greeter2Handler) Subject() string {
	return "helloworld.Greeter2.>"
}

func (h *Greeter2Handler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, _, name, tail, err := nrpc.ParseSubject(
		"helloworld", 0, "Greeter2", 0, msg.Subject)
	if err != nil {
		log.Printf("Greeter2Hanlder: Greeter2 subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "SayHello":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("SayHelloHanlder: SayHello subject parsing failed: %v", err)
			break
		}
		var req HelloRequest2
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("SayHelloHandler: SayHello request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type:    nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context) (proto.Message, error) {
				innerResp, err := h.server.SayHello(ctx, req)
				if err != nil {
					return nil, err
				}
				return &innerResp, err
			}
		}
	default:
		log.Printf("Greeter2Handler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type:    nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("Greeter2Handler: Greeter2 handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type Greeter2Client struct {
	nc         nrpc.NatsConn
	PkgSubject string
	Subject    string
	Encoding   string
	Timeout    time.Duration
}

func NewGreeter2Client(nc nrpc.NatsConn) *Greeter2Client {
	return &Greeter2Client{
		nc:         nc,
		PkgSubject: "helloworld",
		Subject:    "Greeter2",
		Encoding:   "protobuf",
		Timeout:    5 * time.Second,
	}
}

func (c *Greeter2Client) SayHello(req HelloRequest2) (resp HelloReply2, err error) {

	subject := c.PkgSubject + "." + c.Subject + "." + "SayHello"

	// call
	err = nrpc.Call(&req, &resp, c.nc, subject, c.Encoding, c.Timeout)
	if err != nil {
		return // already logged
	}

	return
}

type Client struct {
	nc              nrpc.NatsConn
	defaultEncoding string
	defaultTimeout  time.Duration
	pkgSubject      string
	Greeter2        *Greeter2Client
}

func NewClient(nc nrpc.NatsConn) *Client {
	c := Client{
		nc:              nc,
		defaultEncoding: "protobuf",
		defaultTimeout:  5 * time.Second,
		pkgSubject:      "helloworld",
	}
	c.Greeter2 = NewGreeter2Client(nc)
	return &c
}

func (c *Client) SetEncoding(encoding string) {
	c.defaultEncoding = encoding
	if c.Greeter2 != nil {
		c.Greeter2.Encoding = encoding
	}
}

func (c *Client) SetTimeout(t time.Duration) {
	c.defaultTimeout = t
	if c.Greeter2 != nil {
		c.Greeter2.Timeout = t
	}
}
