// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/nats-rpc/nrpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest2 struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest2) Reset()         { *m = HelloRequest2{} }
func (m *HelloRequest2) String() string { return proto.CompactTextString(m) }
func (*HelloRequest2) ProtoMessage()    {}
func (*HelloRequest2) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *HelloRequest2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest2.Unmarshal(m, b)
}
func (m *HelloRequest2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest2.Marshal(b, m, deterministic)
}
func (m *HelloRequest2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest2.Merge(m, src)
}
func (m *HelloRequest2) XXX_Size() int {
	return xxx_messageInfo_HelloRequest2.Size(m)
}
func (m *HelloRequest2) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest2.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest2 proto.InternalMessageInfo

func (m *HelloRequest2) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply2 struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply2) Reset()         { *m = HelloReply2{} }
func (m *HelloReply2) String() string { return proto.CompactTextString(m) }
func (*HelloReply2) ProtoMessage()    {}
func (*HelloReply2) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *HelloReply2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply2.Unmarshal(m, b)
}
func (m *HelloReply2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply2.Marshal(b, m, deterministic)
}
func (m *HelloReply2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply2.Merge(m, src)
}
func (m *HelloReply2) XXX_Size() int {
	return xxx_messageInfo_HelloReply2.Size(m)
}
func (m *HelloReply2) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply2.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply2 proto.InternalMessageInfo

func (m *HelloReply2) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest2)(nil), "helloworld.HelloRequest2")
	proto.RegisterType((*HelloReply2)(nil), "helloworld.HelloReply2")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x48, 0xcd, 0xc9,
	0xc9, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x48, 0xc9, 0x26, 0xe7, 0xe7, 0xe6, 0xe6, 0xe7, 0xe9, 0xa7, 0x56, 0x94, 0x14, 0x25, 0xc6, 0x83,
	0xe5, 0xf5, 0xf3, 0x8a, 0x0a, 0x92, 0x21, 0x4a, 0x95, 0x94, 0xb9, 0x78, 0x3d, 0x40, 0x8a, 0x83,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x8c, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x75, 0x2e, 0x6e, 0xa8, 0xa2, 0x82, 0x9c,
	0x4a, 0x23, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0x74, 0x98, 0x2a, 0x18, 0xd7,
	0xc8, 0x87, 0x8b, 0xc3, 0xbd, 0x28, 0x35, 0xb5, 0x24, 0xb5, 0xc8, 0x48, 0xc8, 0x81, 0x8b, 0x23,
	0x38, 0xb1, 0x12, 0xac, 0x4f, 0x48, 0x52, 0x0f, 0xc9, 0x8d, 0x28, 0xf6, 0x49, 0x89, 0x63, 0x91,
	0x02, 0xd9, 0xa2, 0xc4, 0xe0, 0x64, 0xc0, 0x25, 0x9d, 0x99, 0xaf, 0x97, 0x0e, 0x72, 0x6c, 0x6a,
	0x45, 0x62, 0x6e, 0x41, 0x4e, 0x6a, 0x31, 0x92, 0x62, 0x27, 0x7e, 0xb0, 0xea, 0x70, 0x10, 0x3b,
	0x00, 0xe4, 0x97, 0x00, 0xc6, 0x24, 0x36, 0xb0, 0xa7, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xd2, 0x0a, 0x22, 0x83, 0x13, 0x01, 0x00, 0x00,
}
